"""EvidencePreprocessing: derives a prompt-time *view* of a Node's raw
transitions -- e.g. annotating each with a discounted return -- without
ever mutating the stored :class:`~storage.models.Transition` rows
themselves. This is the first of two independent stages in
"(program, evidence) -> improved program":

    Node's raw transitions -> EvidencePreprocessor -> processed evidence -> edge (see core/edges.py)

A raw one-step transition ``(s, a, r, s')`` is direct environment evidence.
A return ``G_t`` is a *derived temporal-credit quantity*, computed only from
rewards observed while the same policy/Node was executing -- it belongs to
that Node's own trajectory and must never mix in rewards generated by a
different (e.g. child) Node. Every function here only ever looks at the
transitions it's explicitly given, so that guarantee is structural: whoever
resolves "this Node's own attached evidence" (see
``core.nodes.resolve_node_transitions``) and hands it to
:func:`preprocess_transitions` is what keeps this true, not anything here.

Centralized on purpose -- see the module docstring's warning against
scattering ``if mode == "..."`` branches through UI/training/edge code.
Every caller (Train, MCTS, and the Templates/Edges test-call previews) goes
through :func:`preprocess_transitions` + :func:`render_processed_transitions`
the same way, so ``{{processed_transitions}}`` always means the same thing
regardless of who's rendering it.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from core.formatters import TransitionFormatter
from storage.models import Transition

RAW = "raw"
EPISODIC_RETURN = "episodic_return"
K_STEP_RETURN = "k_step_return"
VALID_PREPROCESSING_MODES = (RAW, EPISODIC_RETURN, K_STEP_RETURN)

# Reasonable defaults -- integrated with the existing configuration system
# (TrainConfig, see core/training.py) rather than hard-coded at every call
# site.
DEFAULT_GAMMA = 0.99
DEFAULT_K = 20

# Exact, stable strings so a rendered prompt (and tests) can rely on them --
# never an arbitrary/truncated return substituted in either case.
UNAVAILABLE_INCOMPLETE_EPISODE = "unavailable (episode incomplete)"
UNAVAILABLE_INSUFFICIENT_STEPS = "unavailable (insufficient future steps)"


@dataclass
class EvidencePreprocessingConfig:
    """How a Node's transitions get represented before being shown to an
    LLM edge -- independent of *which* edge then uses that representation
    (see core/edges.py). ``gamma``/``k`` only matter for
    ``episodic_return``/``k_step_return`` respectively."""

    mode: str = RAW
    gamma: float = DEFAULT_GAMMA
    k: int = DEFAULT_K

    def __post_init__(self):
        if self.mode not in VALID_PREPROCESSING_MODES:
            raise ValueError(f"Unknown preprocessing mode: {self.mode!r} "
                              f"(choices: {VALID_PREPROCESSING_MODES})")
        if self.k <= 0:
            raise ValueError("k must be positive.")


@dataclass
class ProcessedTransition:
    """One transition plus (for ``episodic_return``/``k_step_return``) its
    derived return. ``return_value=None`` with ``return_note`` set means
    the return is genuinely unavailable -- never an arbitrary or
    artificially-truncated substitute (see module docstring)."""

    transition: Transition
    return_value: Optional[float] = None
    return_note: Optional[str] = None


def _group_by_episode(transitions: list[Transition]) -> list[list[Transition]]:
    """Buckets ``transitions`` by ``episode_id`` (first-seen order),
    sorting each bucket by ``step_index`` -- so return calculation is
    correct even if the input wasn't already perfectly chronological
    (e.g. evidence attached out of order via Episodes)."""
    order: list[int] = []
    groups: dict[int, list[Transition]] = {}
    for t in transitions:
        if t.episode_id not in groups:
            groups[t.episode_id] = []
            order.append(t.episode_id)
        groups[t.episode_id].append(t)
    for episode_id in order:
        groups[episode_id].sort(key=lambda t: t.step_index)
    return [groups[episode_id] for episode_id in order]


def _episodic_return(transitions: list[Transition], gamma: float) -> list[ProcessedTransition]:
    """``G_t = r_t + gamma*r_{t+1} + ... `` up to that episode's own
    termination -- never crossing into a different episode. A group whose
    last transition didn't genuinely end (``terminated`` or ``truncated``
    both false -- the Node's evaluation just stopped mid-episode, not the
    environment) gets :data:`UNAVAILABLE_INCOMPLETE_EPISODE` for every one
    of its transitions instead of a fabricated truncated return."""
    results: list[ProcessedTransition] = []
    for group in _group_by_episode(transitions):
        last = group[-1]
        if not (last.terminated or last.truncated):
            results.extend(ProcessedTransition(t, None, UNAVAILABLE_INCOMPLETE_EPISODE) for t in group)
            continue
        n = len(group)
        returns = [0.0] * n
        running = 0.0
        for i in range(n - 1, -1, -1):
            running = group[i].reward + gamma * running
            returns[i] = running
        results.extend(ProcessedTransition(t, g, None) for t, g in zip(group, returns))
    return results


def _k_step_return(transitions: list[Transition], k: int, gamma: float) -> list[ProcessedTransition]:
    """``G_t^(K) = sum_{j=0}^{K-1} gamma^j * r_{t+j}``, computed only from
    rewards within the *same episode* as ``t``. If fewer than ``K``
    rewards remain in that episode: a genuine termination
    (``terminated``/``truncated`` on the group's last transition) makes
    the shorter sum still valid (the episode really ended); otherwise the
    return is :data:`UNAVAILABLE_INSUFFICIENT_STEPS` -- never a shorter
    return substituted for a non-terminal cutoff."""
    results: list[ProcessedTransition] = []
    for group in _group_by_episode(transitions):
        n = len(group)
        group_terminates = group[-1].terminated or group[-1].truncated
        for i in range(n):
            remaining = n - i
            span = k if remaining >= k else (remaining if group_terminates else 0)
            if span == 0:
                results.append(ProcessedTransition(group[i], None, UNAVAILABLE_INSUFFICIENT_STEPS))
                continue
            total = 0.0
            discount = 1.0
            for j in range(span):
                total += discount * group[i + j].reward
                discount *= gamma
            results.append(ProcessedTransition(group[i], total, None))
    return results


def preprocess_transitions(transitions: list[Transition],
                            config: EvidencePreprocessingConfig) -> list[ProcessedTransition]:
    """The single entry point every caller uses -- Train/MCTS (via
    ``core.edges.execute_edge``) and the Templates/Edges test-call
    previews all dispatch through here, so ``{{processed_transitions}}``
    means the same thing everywhere. Never mutates ``transitions``."""
    if not transitions:
        return []
    if config.mode == RAW:
        return [ProcessedTransition(t) for t in transitions]
    if config.mode == EPISODIC_RETURN:
        return _episodic_return(transitions, config.gamma)
    return _k_step_return(transitions, config.k, config.gamma)


def render_processed_transitions(processed: list[ProcessedTransition],
                                  formatter: TransitionFormatter,
                                  full_flags: Optional[list[bool]] = None) -> str:
    """Renders each transition via the existing ``TransitionFormatter``
    (identical to how ``{{transitions}}`` renders one), appending a
    ``return: ...`` line only when this preprocessing mode actually
    produced one -- for ``raw`` mode (or any transition marked
    unavailable) nothing is appended beyond the note, so ``raw`` mode
    reproduces ``{{transitions}}``'s existing output exactly.

    ``full_flags``, if given, must be the same length as ``processed`` --
    see :func:`core.transition_redaction.compute_full_flags`; passed
    through to the formatter unchanged so redaction stays identical
    between ``{{transitions}}`` and ``{{processed_transitions}}`` for the
    same underlying evidence."""
    if not processed:
        return "(no transitions selected)"
    if full_flags is None:
        full_flags = [True] * len(processed)
    parts = []
    for i, p in enumerate(processed):
        text = formatter.format_transition(p.transition, i, full_flags[i])
        if p.return_value is not None:
            text += f"\nreturn: {round(p.return_value, 4)}"
        elif p.return_note is not None:
            text += f"\nreturn: {p.return_note}"
        parts.append(text)
    return "\n\n".join(parts)
